name: "15112024"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Set environment variables
        env:
          VITE_APIKEY: ${{ secrets.APIKEY }}
          VITE_AUTHDOMAIN: ${{ secrets.AUTHDOMAIN }}
          VITE_PROJECT_ID: ${{ secrets.PROJECTID }}
          VITE_STORAGE_BUCKET: ${{ secrets.TORAGEBUCKET }}
          VITE_MESSAGINGSENDERID: ${{ secrets.MESSAGINGSENDERID }}
          VITE_APPID: ${{ secrets.APPID }}
          VITE_MEASUREMENTID: ${{ secrets.MEASUREMENTID }}
        run: echo "Environment variables configured"


      - name: Build project
        run: npm run build

      - name: Deploy to Firebase
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}